### ISSUE TITLE
lost all my collections,  try restore backup from google drive, did't work,  any hep?

### ISSUE THREAD

**Issue by javiercb** [gilgold/tabox#59]
Hello, very good extension so far, but I recently opened the extension and all my saved sessions are gone (they were many and important), I went to the load collection from google backup option and it didn't work either, what can I do? Is there any backup in the extension directory? how to restore it, any help? thank you

**Comment by rille111** [comment]
Exact same happened to me too! Using a different Chrome profile I added the extension, logged in the Tabox account, and the collections suddenly was wiped. Opening on other computers, clicking the Tabox icon, the old collections showed for like 200ms then disappeared with the Sync. 
Nothing happens on restoring from Google Drive.
Lost all my collections I worked hard to keep track on - and feeling very sad ....

**Comment by invasoria** [comment]
Same here. Twice. I now regularly use the "Export all collections" button to back up everything, just in case.

I believe this has happened either when updating Chrome, or adding new google credentials to my profile.

**Comment by gilgold** [comment]
Hey all, thanks for reporting the issue, it seems that in some cases, a blank sync file is created in Google Drive and then it replaces the collections you have locally. 
This will be fixed in the upcoming version (3.5.9) and I will also add an automatic backup to local storage as well so if anything does go wrong again, you can restore. 
Apologies for the inconvenience!

**Comment by gilgold** [comment]
The issue should be resolved in v3.5.9, also you now have automatic backups so if something like this happens again you can always restore. Let me know if you still have a problem, closing this issue for now
